// <auto-generated />
using System;
using BookStoreAPIVer2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookStoreAPIVer2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240904064658_fourth")]
    partial class fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookStoreAPIVer2.Entities.ChamCong", b =>
                {
                    b.Property<int>("MaTk")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BatDauLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("KetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoGioLam")
                        .HasColumnType("integer");

                    b.HasKey("MaTk", "BatDauLam");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.Cthd", b =>
                {
                    b.Property<int>("MaHd")
                        .HasColumnType("integer");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer");

                    b.Property<long>("SoLuongMuaTungCuonSach")
                        .HasColumnType("bigint");

                    b.HasKey("MaHd", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("Cthd");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.CtpnSach", b =>
                {
                    b.Property<int>("MaPns")
                        .HasColumnType("integer");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer");

                    b.Property<long>("GiaSachNhap")
                        .HasColumnType("bigint");

                    b.Property<int>("SoLuongNhapTungCuonSach")
                        .HasColumnType("integer");

                    b.HasKey("MaPns", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CtpnSach");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("integer");

                    b.Property<int>("MaTk")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayTaoHd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TongTienHoaDon")
                        .HasColumnType("bigint");

                    b.HasKey("MaHd");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTenKh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.NhaPhanPhoi", b =>
                {
                    b.Property<int>("MaNpp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNpp"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNpp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNpp");

                    b.ToTable("NhaPhanPhoi");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTk"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Luong")
                        .HasColumnType("bigint");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTaoTaiKhoan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTk");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.PhieuNhapSach", b =>
                {
                    b.Property<int>("MaPns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPns"));

                    b.Property<int>("MaNpp")
                        .HasColumnType("integer");

                    b.Property<int>("MaTk")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhapSach")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TongTienNhapSach")
                        .HasColumnType("bigint");

                    b.HasKey("MaPns");

                    b.ToTable("PhieuNhapSach");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSach"));

                    b.Property<string>("AnhSach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GiaTien")
                        .HasColumnType("bigint");

                    b.Property<int>("MaTl")
                        .HasColumnType("integer");

                    b.Property<string>("Nxb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlHienCo")
                        .HasColumnType("integer");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenTg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaSach");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.TheLoai", b =>
                {
                    b.Property<int>("MaTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTl"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTl");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.ChamCong", b =>
                {
                    b.HasOne("BookStoreAPIVer2.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaTk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.Cthd", b =>
                {
                    b.HasOne("BookStoreAPIVer2.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreAPIVer2.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookStoreAPIVer2.Entities.CtpnSach", b =>
                {
                    b.HasOne("BookStoreAPIVer2.Entities.PhieuNhapSach", "PhieuNhapSach")
                        .WithMany()
                        .HasForeignKey("MaPns")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreAPIVer2.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapSach");

                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
